spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/direct_deal_board_DB
    driver-class-name: org.mariadb.jdbc.Driver
    username: direct_deal_board_user
    password: diretdeal

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: sihwa9592@gmail.com
#    password: fztcvgmztghdzsaj
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true